#Whether it conflicts with the Vanishing Curse
#是否与消失诅咒冲突
conflictWithVanishingCurse = true
#Whether it is treasure enchantment (i.e. will not appear in the Enchantment Table)
#是否是宝物附魔（即不会出现在附魔台中）
isTreasure = true
#Whether to allow the item to disappear after being damaged
#是否允许物品在损坏后消失
allowBreakItem = false
#Max percentage of damage
#最大损坏百分比
#Range: 0 ~ 100
maxDamagePercent = 20
#Min power of enchantment
#最小附魔权重
#Range: 0 ~ 100
minPower = 25
#Power range of enchantment
#附魔权重范围
#Range: 1 ~ 100
powerRange = 50

